In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
import matplotlib.pyplot as plt

In [4]:
data=pd.read_csv("Iris.csv")

In [5]:
X=data.iloc[:,:4].values

In [6]:
y = data['Species'].values

In [7]:
print(data.head())

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa


In [8]:
from sklearn.model_selection import train_test_split

In [9]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

In [10]:
from sklearn.preprocessing import StandardScaler

In [11]:
 sc = StandardScaler()

In [12]:
X_train = sc.fit_transform(X_train)

In [13]:
X_test = sc.transform(X_test)

In [14]:
from sklearn.naive_bayes import GaussianNB

In [15]:
classifier = GaussianNB()

In [16]:
classifier.fit(X_train, y_train)

,"priors priors: array-like of shape (n_classes,), default=NonePrior probabilities of the classes. If specified, the priors are notadjusted according to the data.",None
,"var_smoothing var_smoothing: float, default=1e-9Portion of the largest variance of all features that is added tovariances for calculation stability... versionadded:: 0.20",1e-09


In [17]:
y_pred = classifier.predict(X_test)

In [18]:
print(y_pred)

['Iris-versicolor' 'Iris-versicolor' 'Iris-setosa' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-virginica' 'Iris-versicolor' 'Iris-virginica'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-virginica' 'Iris-virginica'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-virginica'
 'Iris-virginica' 'Iris-versicolor' 'Iris-virginica' 'Iris-setosa'
 'Iris-virginica' 'Iris-setosa' 'Iris-setosa' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-setosa' 'Iris-versicolor' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-setosa' 'Iris-versicolor' 'Iris-setosa'
 'Iris-virginica' 'Iris-setosa' 'Iris-versicolor' 'Iris-virginica'
 'Iris-setosa' 'Iris-virginica' 'Iris-setosa' 'Iris-virginica'
 'Iris-versicolor']


In [19]:
from sklearn.metrics import confusion_matrix

In [20]:
cm=confusion_matrix(y_test, y_pred)

In [21]:
from sklearn.metrics import accuracy_score

In [22]:
print(cm)

[[16  0  0]
 [ 0 16  0]
 [ 0  1 12]]


In [23]:
df = pd.DataFrame({'Real Values':y_test, 'Predicted Values':y_pred})

In [24]:
print(df)

        Real Values Predicted Values
0   Iris-versicolor  Iris-versicolor
1   Iris-versicolor  Iris-versicolor
2       Iris-setosa      Iris-setosa
3   Iris-versicolor  Iris-versicolor
4   Iris-versicolor  Iris-versicolor
5    Iris-virginica   Iris-virginica
6   Iris-versicolor  Iris-versicolor
7    Iris-virginica   Iris-virginica
8   Iris-versicolor  Iris-versicolor
9   Iris-versicolor  Iris-versicolor
10   Iris-virginica   Iris-virginica
11   Iris-virginica   Iris-virginica
12      Iris-setosa      Iris-setosa
13      Iris-setosa      Iris-setosa
14      Iris-setosa      Iris-setosa
15   Iris-virginica   Iris-virginica
16   Iris-virginica   Iris-virginica
17   Iris-virginica  Iris-versicolor
18   Iris-virginica   Iris-virginica
19      Iris-setosa      Iris-setosa
20   Iris-virginica   Iris-virginica
21      Iris-setosa      Iris-setosa
22      Iris-setosa      Iris-setosa
23  Iris-versicolor  Iris-versicolor
24  Iris-versicolor  Iris-versicolor
25      Iris-setosa      Iris-setosa
2

In [25]:
from sklearn.metrics import precision_score, recall_score,accuracy_score

In [26]:
m=accuracy_score(y_test,y_pred)

In [27]:
print("Accuracy : ", accuracy_score(y_test,y_pred))

Accuracy :  0.9777777777777777


In [28]:
print("error rate:-",1-m)

error rate:- 0.022222222222222254


In [29]:
print('Precision:',precision_score(y_test,y_pred,average='micro'))

Precision: 0.9777777777777777


In [30]:
print("Recall Score:",recall_score(y_test,y_pred,average='micro'))

Recall Score: 0.9777777777777777
